### ISSUE TITLE
Action only fetches the first 10 items

### ISSUE THREAD

**Issue by philippbosch** [eliasjcjunior/aws-ssm-parameters-actions#6]
When using the action with `recursive: true` and `paths: …` it will only fetch the first 10 items from SSM and stop. 

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SSM.html#getParametersByPath-property

**Comment by jwarykowski** [comment]
@philippbosch just tested the latest version following my PR and this now works as expected 🎉 Thanks again @eliasjcjunior for the quick turnaround 🙇
